### ISSUE TITLE
--> FSharp.AI.NeuralNetwork or more specialized name

### ISSUE THREAD

**Issue by dsyme** [JahTheDev/FSharp.ML.NeuralNetwork#1]
Hi @JahTheDev 

Just noticed this package come through on twitter. Could I ask you a favour to rename the project and package to use a second level namespace?  We recommend all FSharp.* packages use a second level namespace as well, see the guidelines at http://fsharp.github.io/2014/09/19/fsharp-libraries.html
  See also [this recent issue](https://github.com/xavierzwirtz/FSharp.IO.FileSystem/issues/1).  

Perhaps FSharp.AI.NeuralNetwork.However since the space of AI algorithm implementations is very large, and it may be better to use a more specialized package name.  

Thanks!
 Don

**Comment by JahTheDev** [comment]
Hi @dsyme 

The project has been renamed in 23ee0e05352b638ec78e1cde6175cfade1b3f9de.

Thanks
Jah
